// Generated by rstantools.  Do not edit by hand.

/*
    glmmr is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    glmmr is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with glmmr.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-4-gd72b68b7-dirty
#include <stan/model/model_header.hpp>
namespace model_mcml_bernoulli_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'string', line 23, column 2 to column 22)",
                                                      " (in 'string', line 26, column 2 to column 20)",
                                                      " (in 'string', line 27, column 2 to column 58)",
                                                      " (in 'string', line 28, column 2 to column 83)",
                                                      " (in 'string', line 15, column 2 to column 8)",
                                                      " (in 'string', line 16, column 2 to column 8)",
                                                      " (in 'string', line 17, column 9 to column 10)",
                                                      " (in 'string', line 17, column 2 to column 15)",
                                                      " (in 'string', line 18, column 9 to column 10)",
                                                      " (in 'string', line 18, column 11 to column 12)",
                                                      " (in 'string', line 18, column 2 to column 16)",
                                                      " (in 'string', line 19, column 8 to column 9)",
                                                      " (in 'string', line 19, column 2 to column 17)",
                                                      " (in 'string', line 20, column 2 to column 11)",
                                                      " (in 'string', line 23, column 8 to column 9)",
                                                      " (in 'string', line 3, column 4 to column 41)",
                                                      " (in 'string', line 2, column 60 to line 4, column 3)",
                                                      " (in 'string', line 6, column 4 to column 13)",
                                                      " (in 'string', line 7, column 16 to column 71)",
                                                      " (in 'string', line 7, column 4 to column 71)",
                                                      " (in 'string', line 8, column 16 to column 70)",
                                                      " (in 'string', line 8, column 4 to column 70)",
                                                      " (in 'string', line 9, column 16 to column 65)",
                                                      " (in 'string', line 9, column 4 to column 65)",
                                                      " (in 'string', line 10, column 16 to column 77)",
                                                      " (in 'string', line 10, column 4 to column 77)",
                                                      " (in 'string', line 11, column 4 to column 15)",
                                                      " (in 'string', line 5, column 78 to line 12, column 3)"};
template <bool propto__>
struct partial_sum1_lpdf_rsfunctor__;
template <bool propto__>
struct partial_sum2_lpmf_rsfunctor__;
template <bool propto__, typename T0__>
stan::promote_args_t<T0__>
partial_sum1_lpdf(const std::vector<T0__>& y, const int& start,
                  const int& end, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__>;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    current_statement__ = 16;
    return std_normal_lpdf<false>(
             rvalue(y,
               cons_list(index_min_max(start, end), nil_index_list()), "y"));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct partial_sum1_lpdf_functor__ {
template <bool propto__, typename T0__>
stan::promote_args_t<T0__>
operator()(const std::vector<T0__>& y, const int& start, const int& end,
           std::ostream* pstream__)  const 
{
return partial_sum1_lpdf<propto__>(y, start, end, pstream__);
}
};
template <bool propto__>
struct partial_sum1_lpdf_rsfunctor__ {
template <typename T0__>
stan::promote_args_t<T0__>
operator()(const std::vector<T0__>& y, const int& start, const int& end,
           std::ostream* pstream__)  const 
{
return partial_sum1_lpdf<propto__>(y, start + 1, end + 1, pstream__);
}
};
template <bool propto__, typename T3__>
stan::promote_args_t<stan::value_type_t<T3__>>
partial_sum2_lpmf(const std::vector<int>& y, const int& start,
                  const int& end, const T3__& mu_arg__, const int& type,
                  std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::value_type_t<T3__>>;
  const auto& mu = to_ref(mu_arg__);
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    local_scalar_t__ out;
    out = DUMMY_VAR__;
    
    current_statement__ = 20;
    if (logical_eq(type, 1)) {
      current_statement__ = 19;
      out = bernoulli_logit_lpmf<false>(
              rvalue(y,
                cons_list(index_min_max(start, end), nil_index_list()), "y"),
              rvalue(mu,
                cons_list(index_min_max(start, end), nil_index_list()), "mu"));
    } 
    current_statement__ = 22;
    if (logical_eq(type, 2)) {
      current_statement__ = 21;
      out = bernoulli_lpmf<false>(
              rvalue(y,
                cons_list(index_min_max(start, end), nil_index_list()), "y"),
              stan::math::exp(
                rvalue(mu,
                  cons_list(index_min_max(start, end), nil_index_list()),
                  "mu")));
    } 
    current_statement__ = 24;
    if (logical_eq(type, 3)) {
      current_statement__ = 23;
      out = bernoulli_lpmf<false>(
              rvalue(y,
                cons_list(index_min_max(start, end), nil_index_list()), "y"),
              rvalue(mu,
                cons_list(index_min_max(start, end), nil_index_list()), "mu"));
    } 
    current_statement__ = 26;
    if (logical_eq(type, 4)) {
      current_statement__ = 25;
      out = bernoulli_lpmf<false>(
              rvalue(y,
                cons_list(index_min_max(start, end), nil_index_list()), "y"),
              Phi_approx(
                rvalue(mu,
                  cons_list(index_min_max(start, end), nil_index_list()),
                  "mu")));
    } 
    current_statement__ = 27;
    return out;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct partial_sum2_lpmf_functor__ {
template <bool propto__, typename T3__>
stan::promote_args_t<stan::value_type_t<T3__>>
operator()(const std::vector<int>& y, const int& start, const int& end,
           const T3__& mu, const int& type, std::ostream* pstream__)  const 
{
return partial_sum2_lpmf<propto__>(y, start, end, mu, type, pstream__);
}
};
template <bool propto__>
struct partial_sum2_lpmf_rsfunctor__ {
template <typename T3__>
stan::promote_args_t<stan::value_type_t<T3__>>
operator()(const std::vector<int>& y, const int& start, const int& end,
           std::ostream* pstream__, const T3__& mu, const int& type)  const 
{
return partial_sum2_lpmf<propto__>(y, start + 1, end + 1, mu, type,
         pstream__);
}
};
#include <stan_meta_header.hpp>
class model_mcml_bernoulli final : public model_base_crtp<model_mcml_bernoulli> {
private:
  int N;
  int Q;
  Eigen::Matrix<double, -1, 1> Xb;
  Eigen::Matrix<double, -1, -1> Z;
  std::vector<int> y;
  int type;
 
public:
  ~model_mcml_bernoulli() { }
  
  inline std::string model_name() const final { return "model_mcml_bernoulli"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-4-gd72b68b7-dirty", "stancflags = "};
  }
  
  
  model_mcml_bernoulli(stan::io::var_context& context__,
                       unsigned int random_seed__ = 0,
                       std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_mcml_bernoulli_namespace::model_mcml_bernoulli";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 5;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 5;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 6;
      context__.validate_dims("data initialization","Q","int",
          context__.to_vec());
      Q = std::numeric_limits<int>::min();
      
      current_statement__ = 6;
      Q = context__.vals_i("Q")[(1 - 1)];
      current_statement__ = 7;
      validate_non_negative_index("Xb", "N", N);
      current_statement__ = 8;
      context__.validate_dims("data initialization","Xb","double",
          context__.to_vec(N));
      Xb = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(Xb, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> Xb_flat__;
        current_statement__ = 8;
        assign(Xb_flat__, nil_index_list(), context__.vals_r("Xb"),
          "assigning variable Xb_flat__");
        current_statement__ = 8;
        pos__ = 1;
        current_statement__ = 8;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 8;
          assign(Xb, cons_list(index_uni(sym1__), nil_index_list()),
            Xb_flat__[(pos__ - 1)], "assigning variable Xb");
          current_statement__ = 8;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 9;
      validate_non_negative_index("Z", "N", N);
      current_statement__ = 10;
      validate_non_negative_index("Z", "Q", Q);
      current_statement__ = 11;
      context__.validate_dims("data initialization","Z","double",
          context__.to_vec(N, Q));
      Z = Eigen::Matrix<double, -1, -1>(N, Q);
      stan::math::fill(Z, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> Z_flat__;
        current_statement__ = 11;
        assign(Z_flat__, nil_index_list(), context__.vals_r("Z"),
          "assigning variable Z_flat__");
        current_statement__ = 11;
        pos__ = 1;
        current_statement__ = 11;
        for (int sym1__ = 1; sym1__ <= Q; ++sym1__) {
          current_statement__ = 11;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 11;
            assign(Z,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              Z_flat__[(pos__ - 1)], "assigning variable Z");
            current_statement__ = 11;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 12;
      validate_non_negative_index("y", "N", N);
      current_statement__ = 13;
      context__.validate_dims("data initialization","y","int",
          context__.to_vec(N));
      y = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 13;
      assign(y, nil_index_list(), context__.vals_i("y"),
        "assigning variable y");
      current_statement__ = 14;
      context__.validate_dims("data initialization","type","int",
          context__.to_vec());
      type = std::numeric_limits<int>::min();
      
      current_statement__ = 14;
      type = context__.vals_i("type")[(1 - 1)];
      current_statement__ = 15;
      validate_non_negative_index("gamma", "Q", Q);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += Q;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_mcml_bernoulli_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      std::vector<local_scalar_t__> gamma;
      gamma = std::vector<local_scalar_t__>(Q, DUMMY_VAR__);
      
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= Q; ++sym1__) {
        current_statement__ = 1;
        assign(gamma, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable gamma");}
      {
        int grainsize;
        grainsize = std::numeric_limits<int>::min();
        
        current_statement__ = 2;
        grainsize = 1;
        current_statement__ = 3;
        lp_accum__.add(
          reduce_sum<partial_sum1_lpdf_rsfunctor__<false>>(gamma, grainsize,
            pstream__));
        current_statement__ = 4;
        lp_accum__.add(
          reduce_sum<partial_sum2_lpmf_rsfunctor__<false>>(y, grainsize,
            pstream__, add(Xb, multiply(Z, to_vector(gamma))), type));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_mcml_bernoulli_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      std::vector<double> gamma;
      gamma = std::vector<double>(Q, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= Q; ++sym1__) {
        current_statement__ = 1;
        assign(gamma, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable gamma");}
      for (int sym1__ = 1; sym1__ <= Q; ++sym1__) {
        vars__.emplace_back(gamma[(sym1__ - 1)]);}
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      std::vector<double> gamma;
      gamma = std::vector<double>(Q, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      assign(gamma, nil_index_list(), context__.vals_r("gamma"),
        "assigning variable gamma");
      for (int sym1__ = 1; sym1__ <= Q; ++sym1__) {
        vars__.emplace_back(gamma[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("gamma");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(Q)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= Q; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "gamma" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= Q; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "gamma" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"gamma\",\"type\":{\"name\":\"array\",\"length\":" << Q << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"gamma\",\"type\":{\"name\":\"array\",\"length\":" << Q << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_mcml_bernoulli_namespace::model_mcml_bernoulli;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_mcml_bernoulli_namespace::profiles__;
}
#endif
#endif
