# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.Covariance__new <- function(form_, data_, colnames_) {
    .Call(`_glmmrBase_Covariance__new`, form_, data_, colnames_)
}

.Covariance__Z <- function(xp) {
    .Call(`_glmmrBase_Covariance__Z`, xp)
}

.Covariance__Update_parameters <- function(xp, parameters_) {
    invisible(.Call(`_glmmrBase_Covariance__Update_parameters`, xp, parameters_))
}

.Covariance__D <- function(xp) {
    .Call(`_glmmrBase_Covariance__D`, xp)
}

.Covariance__D_chol <- function(xp) {
    .Call(`_glmmrBase_Covariance__D_chol`, xp)
}

.Covariance__B <- function(xp) {
    .Call(`_glmmrBase_Covariance__B`, xp)
}

.Covariance__Q <- function(xp) {
    .Call(`_glmmrBase_Covariance__Q`, xp)
}

.Covariance__log_likelihood <- function(xp, u_) {
    .Call(`_glmmrBase_Covariance__log_likelihood`, xp, u_)
}

.Covariance__log_determinant <- function(xp) {
    .Call(`_glmmrBase_Covariance__log_determinant`, xp)
}

.Covariance__n_cov_pars <- function(xp) {
    .Call(`_glmmrBase_Covariance__n_cov_pars`, xp)
}

.Covariance__simulate_re <- function(xp) {
    .Call(`_glmmrBase_Covariance__simulate_re`, xp)
}

.Covariance__make_sparse <- function(xp) {
    invisible(.Call(`_glmmrBase_Covariance__make_sparse`, xp))
}

.Covariance__make_dense <- function(xp) {
    invisible(.Call(`_glmmrBase_Covariance__make_dense`, xp))
}

.Covariance__any_gr <- function(xp) {
    .Call(`_glmmrBase_Covariance__any_gr`, xp)
}

.genX <- function(formula, data, colnames) {
    .Call(`_glmmrBase_genX`, formula, data, colnames)
}

.x_names <- function(formula) {
    .Call(`_glmmrBase_x_names`, formula)
}

.re_names <- function(formula) {
    .Call(`_glmmrBase_re_names`, formula)
}

.gen_dhdmu <- function(xb, family, link) {
    .Call(`_glmmrBase_gen_dhdmu`, xb, family, link)
}

.gen_sigma_approx <- function(xb, Z, D, family, link, var_par, attenuate) {
    .Call(`_glmmrBase_gen_sigma_approx`, xb, Z, D, family, link, var_par, attenuate)
}

.attenuate_xb <- function(xb, Z, D, link) {
    .Call(`_glmmrBase_attenuate_xb`, xb, Z, D, link)
}

.dlinkdeta <- function(xb, link) {
    .Call(`_glmmrBase_dlinkdeta`, xb, link)
}

