# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generates the matrix X
#' 
#' Generates the matrix X from a formula and data. This function replicates the functionality of the 
#' R function model.matrix, but is intended to be extended to accomodate linearisation of non-linear functions
#' and other functionality in future versions.
#' @param formula A string specifying the formula
#' @param data A matrix with the data 
#' @param colnames A vector of strings specifying the column names of the data
#' @return A symmetric positive definite covariance matrix
genX <- function(formula, data, colnames) {
    .Call(`_glmmrBase_genX`, formula, data, colnames)
}

#' Gets the names of the fixed effects variables
#' 
#' @param formula A string specifying the formula
#' @return A vector of variable names
x_names <- function(formula) {
    .Call(`_glmmrBase_x_names`, formula)
}

#' Gets the names of the random effects terms
#' 
#' @param formula A string specifying the formula
#' @return A vector of variable names
re_names <- function(formula) {
    .Call(`_glmmrBase_re_names`, formula)
}

#' Generates the inverse GLM iterated weights.
#' 
#' @param xb Vector with mean function value evaluated at fitted model parameters
#' @param family String declaring model family
#' @param link String declaring model link function
#' @return Vector of derivative values
gen_dhdmu <- function(xb, family, link) {
    .Call(`_glmmrBase_gen_dhdmu`, xb, family, link)
}

#' Generates an approximation to the covariance of y
#' 
#' Generates a first-order approximation to the covariance matrix 
#' of y based on the marginal quasi-likelihood. This approximation is
#' exact for the Gaussian-identity model. Used internally by the \link[glmmrBase]{Model} class.
#' @param xb Vector of values of the linear predictor
#' @param Z Random effects design matrix
#' @param D Covariance matrix of the random effects
#' @param family String specifying the family
#' @param link String specifying the link function
#' @param var_par Value of the optional scale parameter
#' @param attenuate Logical indicating whether to use "attenuated" values of the linear predictor
#' @return A matrix
gen_sigma_approx <- function(xb, Z, D, family, link, var_par, attenuate) {
    .Call(`_glmmrBase_gen_sigma_approx`, xb, Z, D, family, link, var_par, attenuate)
}

#' Return marginal expectation with attenuation
#' 
#' The marginal expectation may be better approximated using an attenuation 
#' scheme in non-linear models. This function returns the attenuated linear predictor.
#' Used internally.
#' @param xb Vector of values of the linear predictor
#' @param Z Random effects design matrix
#' @param D Covariance matrix of the random effects
#' @param link String specifying the link function
#' @return A vector
attenuate_xb <- function(xb, Z, D, link) {
    .Call(`_glmmrBase_attenuate_xb`, xb, Z, D, link)
}

#' Partial derivative of link function with respect to linear predictor
#' 
#' Returns the partial derivative of link function with respect to linear predictor.
#' Used internally.
#' @param xb Vector of values of the linear predictor
#' @param link String specifying the link function
#' @return A vector
dlinkdeta <- function(xb, link) {
    .Call(`_glmmrBase_dlinkdeta`, xb, link)
}

